// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsPB.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ProtoMsg {

  #region Messages
  public sealed class NewsGetLGC2S : pb::IMessage {
    private static readonly pb::MessageParser<NewsGetLGC2S> _parser = new pb::MessageParser<NewsGetLGC2S>(() => new NewsGetLGC2S());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NewsGetLGC2S> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed class NewsGetLGS2C : pb::IMessage {
    private static readonly pb::MessageParser<NewsGetLGS2C> _parser = new pb::MessageParser<NewsGetLGS2C>(() => new NewsGetLGS2C());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NewsGetLGS2C> Parser { get { return _parser; } }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    /// <summary>
    ///结果:0获取成功 1无登陆公告
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "NewsInfo" field.</summary>
    public const int NewsInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ProtoMsg.NewsInfo> _repeated_newsInfo_codec
        = pb::FieldCodec.ForMessage(18, global::ProtoMsg.NewsInfo.Parser);
    private readonly pbc::RepeatedField<global::ProtoMsg.NewsInfo> newsInfo_ = new pbc::RepeatedField<global::ProtoMsg.NewsInfo>();
    /// <summary>
    ///公告列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ProtoMsg.NewsInfo> NewsInfo {
      get { return newsInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      newsInfo_.WriteTo(output, _repeated_newsInfo_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      size += newsInfo_.CalculateSize(_repeated_newsInfo_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
          case 18: {
            newsInfo_.AddEntriesFrom(input, _repeated_newsInfo_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
